name: My first workflow

on: push

jobs:
  hello:
    runs-on: ubuntu-latest   

    steps:
      - name: show date
        run: date

      - name: show current folder
        run: pwd

      - name: show files
        run: ls -la
